track_parcel:
  fields:
    tracking_code:
      required: true
      example: "PX1234567890"
      selector:
        text:

untrack_parcel:
  fields:
    tracking_code:
      required: true
      example: "PX1234567890"
      selector:
        text:
